-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

--// vars \\--
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local Event = game:GetService("ReplicatedStorage").Events.Core_Replication

local lastTriggerTime = 0
local interval = 15 -- the time to re-fire (second)

--// heartbeat part \\--
local heartbeatConnection
heartbeatConnection = RunService.Heartbeat:Connect(function()
    local currentTime = tick()

    -- check if interval
    if currentTime - lastTriggerTime >= interval then
        lastTriggerTime = currentTime

        -- fire remote for all
        for _, player in pairs(Players:GetPlayers()) do
            if player.Character and player.Character:FindFirstChild("Head") then
                local head = player.Character.Head
                if head:FindFirstChild("Nametag") then
                    local nametag = head.Nametag
                    if nametag:FindFirstChild("Roleplay_Name") then
                        Event:FireServer(
                            "Text",
                            "Set", 
                            nametag.Biography,
                            "the rp name", -- biography change
                            "Biography"
                        )
                    end
                end
            end
        end
    end
end)
