-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.Core_Replication
Event:FireServer(
    "Text",
    "Set",
    game:GetService("Players").LocalPlayer.Character.Head.Nametag.Role,
    "role", -- the role u want to change
    "Role"
)

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.Core_Replication
Event:FireServer(
    "Text",
    "Change_Color",
    game:GetService("Players").LocalPlayer.Character.Head.Nametag.Role,
    Color3.new(0, 0, 0), -- set the role color,can be changed for more colors
    "Role_Color"
)