-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Events.Core_Replication
Event:FireServer(
    "Text",
    "Set",
    game:GetService("Players").LocalPlayer.Character.Head.Nametag.Role,
    "role", -- the role u want to change
    "Role"
)